### ISSUE TITLE
`Stage::run::<StateTransitionStage>()` causes the initial state to exit and enter again on first run

### ISSUE THREAD

**Issue by tjamaan** [IyesGames/iyes_loopless#10]
By setting NextState on first run in line 122 in `state.rs` the initial state will be switched to itself, thus triggering the exit and enter stages. If exit and enter are expensive (e.g. procedural generation) it will cause needless processing.

Link:
https://github.com/IyesGames/iyes_loopless/blob/cf8e61b2fbf1151171b0feb8199d500c1f6aa20d/src/state.rs#L122

**Comment by tjamaan** [comment]
Ways to fix this:
1. Treat switching a state to itself as an edge-case and require users to set another resource (e.g. `insert_resource(NextState(same_state))` + `insert_resource(SameStateSwitch(true))`) in order to execute exit and enter stages.
1.1. Pros: Only need to check for resource `SameStateSwitch(true)` if current and new state are equal.
1.2. Cons: Clunky if you need to switch state to itself intentionally. New users need to discover the need for `SameStateSwitch` resource.
2. Turn `NextState<T>(pub T)` into `NextState<T>(pub Option<T>)`.
2.1. Pros: Simple to use.
2.2. Cons: Matching an `Option` is not free. (It doesn't cost much though)

**Comment by thebluefish** [comment]
If we're asking the user to insert a resource to transition, I would personally expect the *existence* of the `NextState` resource to indicate that a transition should occur. IMO we should simply not insert this resource by default, and remove it once the transition has procesed.

**Comment by inodentry** [comment]
That was the behavior in 0.1. I changed it, because "repeatedly inserting and removing a resource" (effectively "using a resource as an event") felt weird to me. But you are right, why not, it makes sense. In retrospect, if we are gonna use a resource to trigger a transition, that makes more sense. I guess I should bring it back.

**Comment by inodentry** [comment]
OK, reverted back to the 0.1 states behavior, except now without the `next != current` check (transitioning to the same state as the current is allowed). The `NextState` behaves as you described: insert it to trigger a transition, and it gets auto-removed when the transition is performed.

I consider this bug important enough that I decided to release a `0.3.0` immediately, just for this.

**Comment by tjamaan** [comment]
I confirmed that the fix works. Only the initial state's enter stage is run at the start, and it only ran once.
