### ISSUE TITLE
How to get the new methods on App

### ISSUE THREAD

**Issue by Elogain** [IyesGames/iyes_loopless#13]
Hello

Some background first; Im pretty new to Rust and Bevy.

I've added iyes_loopless to my dependencies (0.3.0 as I use bevy 0.6 still).

However, when trying to use a method like `.add_enter_system` or `add_loopless_state` on the `App::new()` from Bevy I get this error from the compiler:
**no method named `add_enter_system` found for mutable reference `&mut bevy::prelude::App` in the current scope**

I've looked at your examples in this repository and I can't see anything specific I'm missing. My dependency is specified like this:
`[dependencies.iyes_loopless]
version = "0.3.0"`
in my Cargo.toml

I did a `cargo tree -f "{p} {f}"` just to see if there was maybe something with the features, but this was the output:
`├── iyes_loopless v0.3.0 bevy-compat,bevy_core,bevy_utils,default,fixedtimestep,states
│   ├── bevy_core v0.6.0  (*)
│   ├── bevy_ecs v0.6.1 bevy_reflect,default (*)
│   └── bevy_utils v0.6.0  (*)`

Am a bit lost now, would really like to try this way of doing it before just using the Bevy built-in way of doing it.

**Comment by Elogain** [comment]
Note: I've updated to bevy 0.7 now as rapier updated their support to bevy 0.7 as well, I will give this another go (currently using bevy's states but obv run into the very issue of fixed timesteps in specific states :> ).

**Comment by inodentry** [comment]
`use iyes_loopless::prelude::*;`

It will import the "extension traits" that add the methods.
