### ISSUE TITLE
"State Transition not found" when adding an enter_system

### ISSUE THREAD

**Issue by CTred** [IyesGames/iyes_loopless#26]
I have a barebones StatePlugin that crashes whenever I try to `add_enter_system()`. I saw another opened issue mentioning that the API may have some issue with the Plugin architecture, so I tried moving the `add_enter_system` to `main` but did not work either.

this is the error I get:

> thread 'main' panicked at 'State Transiton Stage not found (assuming auto-added label)', /{my_directory}/github.com-1ecc6299db9ec823/iyes_loopless-0.6.1/src/state.rs:306:18

Here's a snippet of my main.rs file

```
fn main() {
    let mut app = App::new();
    app.insert_resource(WindowDescriptor {
        // some not relevant code
    })
    .add_plugins(DefaultPlugins)
    .add_plugin(CameraPlugin)
    .add_plugin(StatePlugin)
    .add_plugin(UiPlugin)
    .add_plugin(GamePlugin);

    app.run();
}
```

and the StatePlugin file:

```
use bevy::prelude::*;
use iyes_loopless::prelude::*;

pub const STARTING_GAME_STATE: GameState = GameState::MainMenu;

#[derive(Debug, Clone, Eq, PartialEq, Hash)]
pub enum GameState {
    MainMenu,
    Options,
    InGame,
}

pub struct StatePlugin;
impl Plugin for StatePlugin {
    fn build(&self, app: &mut App) {
        app
            .add_loopless_state(STARTING_GAME_STATE)
            .add_system(stage_key_bindings)
            .add_enter_system(&GameState::InGame, setup_game); // adding this line crashes the game
    }
}

// This works fine
fn stage_key_bindings(mut commands: Commands, kb_input: Res<Input<KeyCode>>) {
    if kb_input.just_pressed(KeyCode::Escape) {
        commands.insert_resource(NextState(GameState::MainMenu));
    }
}

// Mockup reset_game function when entering a new game
fn setup_game(mut commands: Commands) {
    dbg!("reset_game!");
    commands.insert_resource(NextState(GameState::InGame));
}
```

What am I doing wrong? Thanks!

**Comment by arewerage** [comment]
Try this:

```
.add_enter_system(GameState::InGame, setup_game);
```

**Comment by hankjordan** [comment]
I found that placing .add_loopless_state(X) before I loaded any plugins solved this issue for me.

**Comment by CTred** [comment]
@arewerage thanks. Removing the reference (&) at &GameState::Ingame fixed it. 

Your UPD is also correct. "NextState" from InGame to InGame put me in an endless loop, so removed that as well.
