### ISSUE TITLE
Support for Custom Command Queues? ( I have an Implementation )

### ISSUE THREAD

**Issue by zicklag** [IyesGames/iyes_loopless#30]
Hey there!

For my game I implemented a custom command queue that can be used to flush certain sets of commands before the end of the frame. This is something that was mentioned in the Bevy stageless design, and I wasn't sure if it was something you might want to add to this crate.

I feel like it's a feature other people might want to use, and it'd be good to have in a crate, but I wasn't sure if a new crate would be warranted, or if it'd fit in here, because it's kind of a preview to the stageless bevy design.

Here's a gist with the implementation and usage example. It's really quite simple:

https://gist.github.com/zicklag/3446143d563657d54e292cc7e2c15378

**Comment by zicklag** [comment]
@alice-i-cecile pinging you because you helped start the stageless RFC and might have thoughts on this implementation.

**Comment by alice-i-cecile** [comment]
Oh super interesting; so then we can have different flavors of commands and flush them separately?

IMO this is probably best tackled with a PR to Bevy itself; I think that this should be able to be assessed and implemented independently of the rest of the stageless work.

**Comment by zicklag** [comment]
> Oh super interesting; so then we can have different flavors of commands and flush them separately?

Yep! I think with an `unsafe` implementation of `SystemParam` we can even get ergonomics matching Bevy's built-in `Commands` struct so that you don't have to do `let commands = my_commands.commands()`. I've got to try that out.

> IMO this is probably best tackled with a PR to Bevy itself; I think that this should be able to be assessed and implemented independently of the rest of the stageless work.

Makes sense. I'll close this then and move to Bevy.

**Comment by zicklag** [comment]
While writing an example for how to use this I found that apparently Bevy already flushes the command queues in between stages, by default, unless you explicitly add a stage that doesn't flush the buffers, so this isn't actually necessary, I don't think. 

Since we aren't allowed to insert the exclusive system that flushes the commands anywhere except in it's own stage or at the beginning or end of an existing stage, it doesn't hold any advantage over just letting Bevy do it's default command flushing between stages.

I thought Bevy only flushed the commands at the end of the frame, so I was solving for a non issue. :)
