### ISSUE TITLE
Compile failure when default features are turned off

### ISSUE THREAD

**Issue by martintrumann** [IyesGames/iyes_loopless#34]
When trying to compile the crate without default features this error shows up.
```
  --> iyes_loopless/src/lib.rs:13:20
13 |     pub use crate::state::schedule::ScheduleLooplessStateExt;
   |                    ^^^^^ could not find `state` in the crate root
```

The `#cfg(feature = "app")` in lib.rs only applies to the first import. So the socond one gets included even if `app` isn't enabled.
Also the `app` feature should depend on the `states` feature because the crate also does not compile when only `app` is enabled.

**Comment by inodentry** [comment]
This should be fixed now IIRC.
